### PR TITLE
Upgrade to operator-sdk v0.16.2

### PR DESCRIPTION
**Pull request by grdryn**
Followed upgrade guide at:
https://sdk.operatorframework.io/docs/migration/version-upgrade-guide/#v016x

The reason I didn't go all the way to the latest 0.18.z is that after
0.16.z there were dependency conflicts that might best be solved by
either updating dependencies in openshift/operator-custom-metrics, or
by removing that as a dependency from this operator.

### CODE REVIEW

**Comment by grdryn** [comment]
/cc @RiRa12621 

^since this was suggested at https://github.com/openshift/pagerduty-operator/pull/90/files#r448467970

**Comment by grdryn** [comment]
bump

Bump! Tests pass at least :slightly_smiling_face:

**Comment by jewzaam** [comment]
Discussed with the team and we agree this is a Good Thing.  But not on a Friday.  I'm on PTO next week but will approve and put on hold for deployment and testing in int/stage (side effect of merging this) next week.

/hold

**Comment by jewzaam** [comment]
/approve

cc @jharrington22

**Comment by RiRa12621** [comment]
@jewzaam We could just merge this as it's going int and stage only without the promotion to prod, shouldn't be a big deal even on Friday or weekend 
Cc @jharrington22

**Comment by grdryn** [comment]
Thanks @RiRa12621, I'll rebase my other PR now on top of the new master, which should make it much smaller. :+1:

**Pull request merged**
