### PR TITLE
Wait for incidents to resolve

### PR DESCRIPTION
**Pull request by NautiluX**
* Incident resolution events must be handled before the service gets
deleted, otherwise the incidents stick
* Add unit tests for service deletion
* make external dependencies (time.Sleep + ManageEvent) injectable
* update to go-pagerduty release v1.1.2
* Describe local development setup

### CODE REVIEW

**Comment by jewzaam** [comment]
https://issues.redhat.com/browse/OSD-2148

awesome to see this being worked on..
/approve

**Comment by jewzaam** [comment]
Since the branch name has a 'wip' prefix I assume this isn't ready.  Please remove hold whenever it's time to merge.

/hold

**Comment by NautiluX** [comment]
No it's not really wip, just didn't change the branch after I updated to the official release. Not sure why the tests are still failing though. /retest

**Comment by cblecker** [comment]
I think you'll need to do something like this: https://github.com/openshift/deadmanssnitch-operator/commit/a9b68dc85916b436fc5c6eb197f8c1a127a04e8f

The problem is the build cluster moved to a v4 cluster, and it doesn't work with the OPERATOR_PATH env anymore and I'm not sure why.

**Comment by NautiluX** [comment]
/hold cancel
sorry for the confusing branch name

**Comment by NautiluX** [comment]
> I think you'll need to do something like this: [openshift/deadmanssnitch-operator@a9b68dc](https://github.com/openshift/deadmanssnitch-operator/commit/a9b68dc85916b436fc5c6eb197f8c1a127a04e8f)
> 
> The problem is the build cluster moved to a v4 cluster, and it doesn't work with the OPERATOR_PATH env anymore and I'm not sure why.

done.

**Pull request merged**
