### PR TITLE
Adding unit testing for clusterdeployment_controller and syncset_controller

### LINKED ISSUE #23: Create unit tests for controllers

### PR DESCRIPTION
**Pull request by blrm**
This PR adds unit testing for the clusterdeployment_controller and the syncset_controller. In order to make this possible, the pagerduty service code had to be refactored slightly so that the pagerduty API client could be mocked. 

This resolves #23 and #33

### CODE REVIEW

**Comment by rogbas** [comment]
/lgtm

It's covering the main use cases we have

**Comment by stevekuznetsov** [comment]
@rogbas `tide` cannot auto-merge this repo because of the approving review that has been required in the GitHub UI. Please un-require that so that the automation can function.

```json
{
  "base-sha": "5382aa06ef9d90c6fb8d45f506943a757f45ba88",
  "branch": "master",
  "component": "tide",
  "controller": "sync",
  "error": "failed merging [47]: [PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? At least 1 approving review is required by reviewers with write access.]",
  "file": "prow/tide/tide.go:356",
  "func": "k8s.io/test-infra/prow/tide.(*Controller).Sync.func2",
  "level": "error",
  "msg": "Error syncing subpool.",
  "org": "openshift",
  "repo": "pagerduty-operator",
  "time": "2019-06-18T21:51:02Z"
}
```

**Comment by stevekuznetsov** [comment]
@rogbas please change your configuration. This is ridiculous.

/hold

**Comment by rogbas** [comment]
I was trying to unlock it after giving an approval review, but it didn't work.

It was escalated to the admins of this repo, I don't have rights to change that config.

**Pull request merged**
